sdk/src/main/scala/com/horizen/certificatesubmitter/CertificateSubmitter.scala
Step 1 at fixing #173 issue related to increasing memory consumption.
=> Serializing Proof generation in a single thread queue

qa/README.md, qa/SidechainTestFramework/sc_test_framework.py, qa/SidechainTestFramework/scutil.py
parametrized a couple of lines in the testframework to let external tests in sidechain applications to run
=> Issue 197 - external testframework support

sdk/src/main/scala/com/horizen/websocket/client/WebSocketCommunicationClient.scala, sdk/src/main/scala/com/horizen/websocket/server/WebSocketServer.scala, sdk/src/test/scala/com/horizen/utils/CountDownLatchController.scala, sdk/src/test/scala/com/horizen/websocket/client/WebSocketCommunicationClientTest.scala, sdk/src/test/scala/com/horizen/websocket/server/WebSocketServerEndpointTest.scala
Speed up Unit websocket related unit tests from 1m+ to ~2s.
Minor refactoring.
=> Websocket Unit tests optimization.

sdk/src/main/java/com/horizen/cryptolibprovider/CommonCircuit.java, sdk/src/main/java/com/horizen/cryptolibprovider/CswCircuitImplZendoo.java, sdk/src/main/java/com/horizen/cryptolibprovider/ThresholdSignatureCircuitImplZendoo.java
PR depends on https://github.com/HorizenOfficial/zendoo-sc-cryptolib/pull/77
=> DLOG keys management.

qa/run_sc_tests.py, qa/sc_backward_transfer.py, qa/sc_bwt_minimum_value.py, sdk/src/main/java/com/horizen/transaction/SidechainTransaction.java, sdk/src/main/java/com/horizen/utils/ZenCoinsUtils.java, sdk/src/main/resources/api/sidechainApi.yaml, sdk/src/main/scala/com/horizen/api/http/SidechainTransactionApiRoute.scala, sdk/src/test/java/com/horizen/transaction/RegularTransactionTest.java, sdk/src/test/java/com/horizen/transaction/SidechainCoreTransactionTest.java, sdk/src/test/scala/com/horizen/fixtures/BoxFixture.scala
This PR introduced a minimum coin amount for withdrawal requests. Withdrawal transactions with a lower amount of coins will be rejected.
=> Added threshold for minimum backward transfer.

sdk/src/main/java/com/horizen/transaction/AbstractRegularTransaction.java
Improvement for product team needs.
Tag: 0.3.0-beta
=> AbstractRegularTransaction improvement.

evm/src/main/java/com/horizen/evm/LibEvm.java, evm/src/main/java/com/horizen/evm/StateDB.java, evm/src/main/java/com/horizen/evm/interop/SnapshotParams.java, evm/src/test/java/com/horizen/evm/StateDBTest.java, libevm/lib/service_state.go, libevm/lib/service_test.go
Expose `snapshot` and `revertToSnapshot` methods via StateDB interface.
=> add Snapshot/Revert to StateDB interface

sdk/src/main/java/com/horizen/account/api/rpc/service/EthService.java, sdk/src/main/scala/com/horizen/account/api/http/AccountEthRpcRoute.scala, sdk/src/main/scala/com/horizen/api/http/ApiResponseUtil.scala, sdk/src/test/java/com/horizen/account/api/rpc/service/EthServiceTest.java
Changes after testing with metamask
=> add api response without result wrapper, add options route

sdk/pom.xml, sdk/src/main/java/com/horizen/account/proof/SignatureSecp256k1.java, sdk/src/main/java/com/horizen/account/secret/PrivateKeySecp256k1.java, sdk/src/test/java/com/horizen/account/proof/SignatureSecp256k1Test.java, sdk/src/test/java/com/horizen/account/proposition/AddressPropositionSerializerTest.java, sdk/src/test/java/com/horizen/account/proposition/AddressPropositionTest.java, sdk/src/test/java/com/horizen/account/secret/PrivateKeySecp256k1Test.java
Add some more tests for secret / proposition and do some improvements
=> add tests for secret and proposition

README.md, ci/README.md
Adding README file for new SNAPSHOT build functionality as well as explanation on new set_version.sh script
=> Added README file for building SNAPSHOT versions

evm/src/main/java/com/horizen/evm/LibEvm.java, evm/src/main/java/com/horizen/evm/TrieHasher.java, evm/src/main/java/com/horizen/evm/interop/HashParams.java, evm/src/test/java/com/horizen/evm/EvmTest.java, evm/src/test/java/com/horizen/evm/LibEvmTestBase.java, evm/src/test/java/com/horizen/evm/StateDBTest.java, evm/src/test/java/com/horizen/evm/TrieHasherTest.java, libevm/lib/service_hash.go, libevm/lib/service_test.go
- add merkle trie hasher to libevm
- add interop code
- refactor evm interop tests to multiple units
=> Ethereum compatible merkle trie hasher

README.md
… field when you run the node as a docker container
=> Sdk 234 - README update about running sidechain node on docker

qa/run_sc_tests.py, qa/sc_csw_in_fee_payment.py, sdk/src/main/scala/com/horizen/SidechainWalletCswDataProvider.scala
Verified that the FeePaymentBoxes are included in the SidechainWalletCswDataStorage with a new Python test.
=> [SDK-213] Added python test to check FeePaymentBoxes inside CSW

sdk/src/main/java/com/horizen/account/event/Anonymous.java, sdk/src/main/java/com/horizen/account/event/EthereumEvent.java, sdk/src/main/java/com/horizen/account/event/Indexed.java, sdk/src/main/java/com/horizen/account/event/Parameter.java, sdk/src/test/java/com/horizen/account/event/EthereumEventTest.java, sdk/src/test/scala/com/horizen/account/event/TestEvents.scala
=> EVM Event Creation Utility

sdk/src/test/scala/com/horizen/forger/ForgerGenerationRateTest.scala
Test for checking occurrence slot leadership with different stake amounts and forger numbers.
=> Added ForgerGenerationRateTest.

examples/simpleapp/src/main/java/com/horizen/examples/AppForkConfigurator.java, examples/simpleapp/src/main/java/com/horizen/examples/SimpleAppModule.java, sdk/src/main/scala/com/horizen/SidechainApp.scala, sdk/src/main/scala/com/horizen/SidechainAppModule.scala, sdk/src/main/scala/com/horizen/fork/BaseConsensusEpochFork.scala, sdk/src/main/scala/com/horizen/fork/BaseMainchainHeightFork.scala, sdk/src/main/scala/com/horizen/fork/ForkConfigurator.scala, sdk/src/main/scala/com/horizen/fork/ForkManager.scala, sdk/src/main/scala/com/horizen/fork/SidechainFork1.scala, sdk/src/test/scala/com/horizen/fork/ForkConfiguratorTest.scala, sdk/src/test/scala/com/horizen/fork/ForkManagerTest.scala, sdk/src/test/scala/com/horizen/fork/SimpleForkConfigurator.scala
Introduced a ForkMaanger. The mechanism that allows getting Mainchain or Sidechain for specified MainchainHeight or SidechainConsensusEpochNumebr.
Description of this feature can be found on SDK Notion - https://www.notion.so/horizen-labs/Fork-Manager-c28433d6d0ec4ef8adb9dc14c94e99e8
=> Added ForkManager and tests.

sdk/src/main/scala/com/horizen/SidechainApp.scala
Fixed an error from Python tests.
=> Fixed ForkManager init error.

examples/simpleapp/src/main/resources/sc_settings.conf, examples/simpleapp/src/main/resources/settings_basic.conf, sdk/src/main/resources/sidechain-sdk-settings.conf
Replace PR https://github.com/HorizenOfficial/Sidechains-SDK/pull/451
=> Config files: apiKeyHash cleanup.

qa/SidechainTestFramework/scutil.py, qa/sc_storage_recovery_with_csw.py, qa/sc_storage_recovery_without_csw.py, tools/dbtool/src/main/java/com/horizen/DbTool.java, tools/dbtool/src/main/java/com/horizen/DbToolCommandProcessor.java
This PR replaces the PR https://github.com/HorizenOfficial/Sidechains-SDK/pull/435
=> SDK-166 - add custom storage names parameter to DbTool

qa/sc_evm_bootstrap.py, sdk/src/main/scala/com/horizen/account/api/rpc/service/EthService.scala
API documentation was already correct, no further changes needed.
=> add optional tag and null case handling

qa/SidechainTestFramework/scutil.py, qa/httpCalls/transaction/sendCoinsToAddress.py, qa/run_sc_tests.sh, qa/sc_fork_one_forced_tx.py, sdk/src/main/scala/com/horizen/SidechainApp.scala, sdk/src/main/scala/com/horizen/SidechainState.scala, sdk/src/main/scala/com/horizen/api/http/SidechainBlockActor.scala, sdk/src/main/scala/com/horizen/api/http/SidechainBlockApiRoute.scala, sdk/src/main/scala/com/horizen/api/http/SidechainTransactionApiRoute.scala, sdk/src/main/scala/com/horizen/forge/ForgeMessageBuilder.scala, sdk/src/main/scala/com/horizen/forge/Forger.scala, sdk/src/test/scala/com/horizen/SidechainStateTest.scala, sdk/src/test/scala/com/horizen/api/http/SidechainApiRouteTest.scala, sdk/src/test/scala/com/horizen/api/http/SidechainTransactionApiRouteTest.scala
https://horizenlabs.atlassian.net/browse/SDK-400
Now all checks that happen at the edge block(block that enables new epoch) are also checked in accordance to new rules that new epoch enables.
=> SDK-400 - Fix fork1 usage for transactions in mempool. 

.travis.yml
Bumping vm size for the build to x-large
=> Increasing travis vm size

CHANGELOG.md, README.md, ci/run_sc.sh, examples/simpleapp/README.md, examples/simpleapp/mc_sc_workflow_example.md, examples/simpleapp/pom.xml, examples/simpleapp/src/main/resources/sc_settings.conf, examples/simpleapp/src/main/resources/settings_basic.conf, pom.xml, qa/SidechainTestFramework/sc_test_framework.py, qa/SidechainTestFramework/scutil.py, qa/httpCalls/transaction/createCoreTransaction.py, qa/httpCalls/transaction/findTransactionByID.py, qa/httpCalls/transaction/sendTransaction.py, qa/httpCalls/wallet/allBoxesOfType.py, qa/resources/template.conf, qa/resources/template_predefined_genesis.conf, qa/run_sc_tests.py, qa/sc_big_block.py, sdk/pom.xml, sdk/src/main/resources/sidechain-sdk-settings.conf, tools/dbtool/pom.xml, tools/sctool/pom.xml
Changelog:
1. Blocks network propagation fixed: allow to send blocks greater than 1 Mb.
=> Release 0.4.3

sdk/src/main/java/com/horizen/account/api/rpc/types/EthereumAccountProof.java, sdk/src/main/scala/com/horizen/account/api/rpc/service/EthService.scala
- fix response serialization of `eth_getProof`
=> Fix eth_getProof

sdk/src/main/scala/com/horizen/account/api/rpc/service/EthService.scala
Add RPC functions:
- eth_accounts
- eth_sendTransaction
- eth_sign (untested)
=> Add more RPC functions

sdk/src/main/java/com/horizen/settings/LogInitializer.java, sdk/src/main/resources/log4j2.xml, tools/sctool/src/main/java/com/horizen/ScBootstrappingTool.java
Fix log initilization of the SC bootstrapping tool, the recent addition of the `logRootLevel` broke it.
=> fix logging of SC bootstrapping tool

sdk/src/main/scala/com/horizen/AbstractHistory.scala, sdk/src/main/scala/com/horizen/utils/WithdrawalEpochUtils.scala, sdk/src/main/scala/com/horizen/websocket/server/SidechainNodeChannelImpl.scala
change AbstractHistory and make sidechain node channel impl more generic
=> sdk34: withdrawal epoch utils

qa/SidechainTestFramework/account/ac_chain_setup.py, qa/SidechainTestFramework/scutil.py, qa/sc_evm_storage_recovery.py, tools/sctool/src/main/java/com/horizen/ScBootstrappingToolCommandProcessor.java
use key generator, remove comment and avoid using block version as marker for account or utxo model
=> SC bootstrap tool improvements

sdk/src/main/scala/com/horizen/account/api/rpc/service/EthService.scala, sdk/src/test/scala/com/horizen/account/api/rpc/service/EthServiceTest.scala
- eth_syncing rpc method and ut
=> EVM-548 - eth_syncing rpc method

sdk/src/main/java/com/horizen/account/api/rpc/types/EthereumBlockView.java, sdk/src/main/java/com/horizen/account/api/rpc/types/EthereumTransactionView.java, sdk/src/main/scala/com/horizen/account/api/rpc/service/EthService.scala
In this pull request: 
- eth_getBlockByNumber and eth_getBlockByHash response serialization fixes (issues tracked in the task EVM-595 and EVM-600)
=> EVM-595 - eth_getBlock methods response fix

qa/sc_evm_test_debug_methods.py, sdk/src/main/scala/com/horizen/account/api/rpc/service/EthService.scala
- debug_traceBlockByHash rpc method implementation
- python test sc_evm_test_debug_methods updated
=> EVM-552 - debug_traceBlockByHash rpc method

sdk/src/main/scala/com/horizen/SidechainState.scala
Jira ticket: https://horizenlabs.atlassian.net/browse/SDK-699
=> Non-ceasing sidechains: fix certificate validation in the state.

sdk/src/main/scala/com/horizen/account/api/http/AccountTransactionApiRoute.scala, sdk/src/test/scala/com/horizen/account/api/http/AccountNodeViewUtilMocks.scala, sdk/src/test/scala/com/horizen/account/api/http/AccountTransactionApiRouteTest.scala
Fixed possible wrong nonce issue. Secret and nonce are retrieved only once what's prevents wrong nonce usage.
Created unit test for this case.
=> Fixed possible incorrect nonce during EIP1559transaction creation.

sdk/src/main/java/com/horizen/account/api/rpc/types/TransactionArgs.java
Fixed potential null pointer dereference.
=> Fixed potential null pointer dereference.

evm/src/test/java/com/horizen/evm/StateDBTest.java
remove ignore of proof test, add changes to test flow for proof
=> getProof test changes

examples/simpleapp/src/main/resources/sc_settings.conf, examples/simpleapp/src/main/resources/settings_basic.conf, qa/resources/template.conf, qa/resources/template_predefined_genesis.conf, sdk/src/main/scala/com/horizen/AbstractSidechainApp.scala, sdk/src/main/scala/com/horizen/SidechainApp.scala, sdk/src/main/scala/com/horizen/SidechainSettings.scala, sdk/src/main/scala/com/horizen/SidechainSettingsReader.scala, sdk/src/main/scala/com/horizen/account/AccountSidechainApp.scala, sdk/src/main/scala/com/horizen/account/forger/AccountForger.scala, sdk/src/main/scala/com/horizen/forge/Forger.scala, sdk/src/main/scala/com/horizen/websocket/client/DefaultWebSocketReconnectionHandler.scala, sdk/src/main/scala/com/horizen/websocket/client/WebSocketConnectorImpl.scala, sdk/src/test/resources/sc_node_holder_fixter_settings.conf, sdk/src/test/scala/com/horizen/forge/ForgerTest.scala, sdk/src/test/scala/com/horizen/websocket/client/WebSocketChannelImplTest.scala
Signed-off-by: sgonta <sgonta@horizenlabs.io>
=> Web socket settings and enabling of connections

qa/README.md, sdk/pom.xml, sdk/src/main/scala/com/horizen/SidechainNodeViewHolder.scala, sdk/src/main/scala/com/horizen/account/websocket/WebSocketAccountServerEndpoint.scala, sdk/src/main/scala/com/horizen/account/websocket/WebSocketAccountServerImpl.scala, sdk/src/main/scala/com/horizen/account/websocket/data/Subscription.scala, sdk/src/main/scala/com/horizen/websocket/client/WebSocketConnectorImpl.scala, sdk/src/main/scala/com/horizen/websocket/server/WebSocketServerBaseImpl.scala, sdk/src/main/scala/com/horizen/websocket/server/WebSocketServerEndpoint.scala, sdk/src/main/scala/com/horizen/websocket/server/WebSocketServerImpl.scala, sdk/src/test/scala/com/horizen/websocket/client/WebSocketServerEchoEndpoint.scala, sdk/src/test/scala/com/horizen/websocket/client/WebSocketServerPushEndpoint.scala, sdk/src/test/scala/com/horizen/websocket/server/WebSocketServerEndpointTest.scala
Signed-off-by: sgonta <sgonta@horizenlabs.io>
=> Upgrade websocket library https://horizenlabs.atlassian.net/browse/SDK-331

qa/sc_evm_test_metamask_related.py, sdk/src/main/java/com/horizen/account/api/rpc/types/EthereumBlockView.java, sdk/src/main/java/com/horizen/account/api/rpc/types/EthereumTransactionView.java, sdk/src/test/scala/com/horizen/account/api/rpc/service/EthServiceTest.scala
Delete author in EthereumBlockView - the rest mentioned in [612](https://horizenlabs.atlassian.net/jira/software/c/projects/EVM/boards/12?modal=detail&selectedIssue=EVM-612&assignee=624db49aad6b7e006aa91a3c) are needed and the behavior is the same to what ethereum does.
=> Check required fields for getBlock... and getTransactionByHash

sdk/src/main/java/com/horizen/box/CoreBoxesIdsEnum.java, sdk/src/main/java/com/horizen/box/CrossChainRedeemMessageBox.java, sdk/src/main/java/com/horizen/box/CrossChainRedeemMessageBoxSerializer.java, sdk/src/main/java/com/horizen/box/data/CrossChainRedeemMessageBoxData.java, sdk/src/main/java/com/horizen/box/data/CrossChainRedeemMessageBoxDataSerializer.java, sdk/src/main/java/com/horizen/cryptolibprovider/Sc2scCircuit.java, sdk/src/main/java/com/horizen/cryptolibprovider/implementations/Sc2scImplZendoo.java, sdk/src/main/java/com/horizen/transaction/AbstractCrossChainRedeemTransaction.java, sdk/src/main/java/com/horizen/validation/AbstractCrossChainRedeemTransactionValidator.java, sdk/src/main/java/com/horizen/validation/TransactionValidator.java, sdk/src/main/scala/com/horizen/SidechainState.scala, sdk/src/main/scala/com/horizen/account/state/StateTransition.scala, sdk/src/main/scala/com/horizen/storage/SidechainStateStorage.scala, sdk/src/test/java/com/horizen/box/CrossChainRedeemMessageBoxSerializerTest.java, sdk/src/test/java/com/horizen/box/data/CrossChainRedeemMessageBoxDataSerializerTest.java, sdk/src/test/java/com/horizen/validation/AbstractCrossChainRedeemTransactionValidatorTest.java, sdk/src/test/scala/com/horizen/SidechainStateTest.scala, sdk/src/test/scala/com/horizen/integration/SidechainStateIntegrationTest.scala, sdk/src/test/scala/com/horizen/integration/storage/SidechainStateStorageTest.scala, sdk/src/test/scala/com/horizen/storage/SidechainStateStorageTest.scala
Added:
- AbstractCrossChainRedeemTransaction
- AbstractCrossChainRedeemTransactionValidator
- RedeemBoxData + serializer
- RedeemBox + serializer
- unit tests
[Technical document](https://docs.google.com/document/d/1yQZiQShZnv9BgIc6Q8XiO1jQQxvzF0bc5xp018_00ck)
=> SDK-744: add redeem message side [UTXO]

qa/run_sc_tests.sh, qa/sc_evm_sync_status.py, sdk/src/main/java/io/horizen/network/SyncStatus.java, sdk/src/main/scala/io/horizen/account/AccountSidechainApp.scala, sdk/src/main/scala/io/horizen/account/api/http/route/AccountEthRpcRoute.scala, sdk/src/main/scala/io/horizen/account/api/rpc/service/EthService.scala, sdk/src/main/scala/io/horizen/network/SyncStatusActor.scala, sdk/src/main/scala/io/horizen/network/SyncStatusUtil.scala, sdk/src/test/scala/io/horizen/account/api/http/route/AccountEthRpcRouteMock.scala, sdk/src/test/scala/io/horizen/account/api/rpc/service/EthServiceTest.scala, sdk/src/test/scala/io/horizen/api/http/SidechainApiMockConfiguration.scala, sdk/src/test/scala/io/horizen/network/SyncStatusUtilTest.scala
- node syncing status actor
- _eth_syncing_ rpc method
- python test
Design doc for this PR can be found at the following link: https://docs.google.com/document/d/1CWwFnXB3GVEsSMSAwlZgawB1kqBEUWpbqZXygDuhTw8/edit?usp=sharing
=> EVM-683 - eth_syncing method

sdk/src/main/java/io/horizen/account/secret/PrivateKeySecp256k1Creator.java
According to the comments by NCC
=> Secp256k1 key generation domain has been updated.

sdk/src/main/java/io/horizen/SensitiveString.java, sdk/src/main/java/io/horizen/utils/CheckedCompanion.scala, sdk/src/main/scala/io/horizen/SensitiveStringer.scala, sdk/src/main/scala/io/horizen/SidechainSettings.scala, sdk/src/main/scala/io/horizen/api/http/route/WalletBaseApiRoute.scala
- add `SensitiveStringer` trait which omits values from `toString` calls that are annotated with `SensitiveString`
- use `SensitiveString` on all settings classes
=> fix SidechainSettings logging

qa/SidechainTestFramework/account/ac_chain_setup.py, qa/sc_evm_closed_forger.py
Additional code added for open forger, ensuring a new node can forge blocks once opened.
Fixed typo and bug in ac chain setup
=> open forger additional tests, fix ac chain setup

sdk/src/main/scala/io/horizen/utils/WithdrawalEpochUtils.scala, sdk/src/test/scala/io/horizen/utils/WithdrawalEpochUtilsTest.scala
Fix for method `getWithdrawalEpochInfo` for handling the case of start from end of epoch and jump directly to the next end of epoch with the maximum number of mc ref blocks
=> End of withdrawal epoch not correctly handled by Account State

sdk/src/main/scala/io/horizen/api/http/route/SidechainNodeApiRoute.scala, sdk/src/test/scala/io/horizen/api/http/SidechainApiMockConfiguration.scala, sdk/src/test/scala/io/horizen/api/http/route/SidechainApiRouteTest.scala, sdk/src/test/scala/io/horizen/api/http/route/SidechainNodeApiRouteTest.scala
[Jira ticket](https://horizenlabs.atlassian.net/browse/SDK-922)
=> SDK-922 : added missing peers list APIs

sdk/src/main/resources/account/api/accountApi.yaml, sdk/src/main/resources/utxo/api/sidechainApi.yaml
[Jira ticket](https://horizenlabs.atlassian.net/browse/SDK-1050?atlOrigin=eyJpIjoiMDc4ZGY2MzA3ZTk0NDk3MTlmOTgxYjIxYWNkNTA4MjEiLCJwIjoiaiJ9)
Both UTXO and Account model yaml files updated
=> dd/sdk 1050 : Update yaml file with SPARKZ peer list APIs

sdk/src/main/scala/io/horizen/AbstractSidechainNodeViewHolder.scala, sdk/src/main/scala/io/horizen/forge/AbstractForgeMessageBuilder.scala, sdk/src/main/scala/io/horizen/history/AbstractHistory.scala
Added additional logs to help make statistic on blocks creation time and forks length.
=> Added additional logs

README.md
Updated Readme.md with accurate Latus description.
=> Updated Readme with accurate Latus description.

sdk/src/main/scala/io/horizen/api/http/client/SecureEnclaveApiClient.scala, sdk/src/test/scala/io/horizen/api/http/client/SecureEnclaveApiClientTest.scala
[Jira ticket](https://horizenlabs.atlassian.net/browse/SDK-1156?atlOrigin=eyJpIjoiMTg4ODM0OTIwOWM4NDQ3NDg3NWEyMzJiNmVlMGNiN2MiLCJwIjoiaiJ9)
=> secure enclave http request headers added

CHANGELOG.md, sdk/src/main/scala/io/horizen/account/mempool/MempoolMap.scala, sdk/src/main/scala/io/horizen/account/mempool/exception/MempoolException.scala, sdk/src/main/scala/io/horizen/account/state/AccountState.scala, sdk/src/test/scala/io/horizen/account/mempool/AccountMemoryPoolTest.scala, sdk/src/test/scala/io/horizen/account/mempool/MempoolMapTest.scala, sdk/src/test/scala/io/horizen/account/mempool/MempoolMapUpdateTest.scala, sdk/src/test/scala/io/horizen/account/state/AccountStateTest.scala
See [SDK-1221](https://horizenlabs.atlassian.net/browse/SDK-1221)
[SDK-1221]: https://horizenlabs.atlassian.net/browse/SDK-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SDK-1221 Reject TXs below baseFee fork value from mempool

sdk/src/main/scala/io/horizen/storage/SidechainSecretStorage.scala, sdk/src/main/scala/io/horizen/wallet/AbstractWallet.scala, sdk/src/test/scala/io/horizen/account/wallet/AccountWalletTest.scala, sdk/src/test/scala/io/horizen/integration/storage/SidechainSecretStorageTest.scala
[Jira ticket](https://horizenlabs.atlassian.net/browse/SDK-809?atlOrigin=eyJpIjoiYmFlZmRjYWM4ZDNiNDkxN2FiZGExOTQxNjc0MTMzNmUiLCJwIjoiaiJ9)
=> SDK 809 - NCC Audit suggestion: generateNextSecret

qa/sc_evm_mc_addr_ownership.py, sdk/src/main/scala/io/horizen/account/api/http/route/AccountTransactionApiRoute.scala, sdk/src/main/scala/io/horizen/account/state/McAddrOwnershipMsgProcessor.scala, sdk/src/main/scala/io/horizen/account/state/ScAddrOwnershipLinkedList.scala, sdk/src/main/scala/io/horizen/account/state/ScAddressRefsLinkedList.scala
Last fixes to the code review that erroneously had not been committed.
Also, added support for different formats of sc address to zendao http api cmd
=> missing fixes after code review and improvings in http api cmds

CHANGELOG.md
=> improved changelog

qa/sc_evm_consensus_parameters_fork_with_mainchain_forks.py, qa/sc_evm_consensus_parameters_fork_with_sidechain_forks.py
Consensus parameters change python tests
[SDK-1413](https://horizenlabs.atlassian.net/browse/SDK-1413)
- python test (`sc_evm_consensus_parameters_fork_with_sidechain_forks.py`) to check correctness of the consensus parameter change and slot coefficient change activation with sidechain forks
- python test (`sc_evm_consensus_parameters_fork_with_mainchain_forks.py`) to check correctness of the consensus parameter change and slot coefficient change activation with mainchain forks
[SDK-1413]: https://horizenlabs.atlassian.net/browse/SDK-1413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SDK-1413 - consensus parameters change python tests

CHANGELOG.md, README.md, ci/run_sc.sh, examples/README.md, examples/account/evmapp/pom.xml, examples/account/evmapp_sctool/pom.xml, examples/mc_sc_workflow_example.md, examples/utxo/simpleapp/pom.xml, examples/utxo/utxoapp_sctool/pom.xml, pom.xml, qa/SidechainTestFramework/sc_test_framework.py, qa/SidechainTestFramework/scutil.py, qa/SidechainTestFramework/secure_enclave_http_api_server.py, sdk/pom.xml, sdk/src/test/scala/io/horizen/api/http/route/MainchainBlockApiRouteTest.scala, sdk/src/test/scala/io/horizen/api/http/route/SidechainApiRouteTest.scala, sdk/src/test/scala/io/horizen/utxo/network/SidechainNodeViewSynchronizerTest.scala, tools/dbtool/pom.xml, tools/sctool/pom.xml, tools/sidechains-sdk-account_sctools/pom.xml, tools/sidechains-sdk-utxo_sctools/pom.xml, tools/signingtool/pom.xml
=> bump version to 0.7.2

sdk/src/main/scala/io/horizen/account/forger/AccountForgeMessageBuilder.scala
Fixed issue with different fee payments.
SDK-1166 https://horizenlabs.atlassian.net/browse/SDK-1166
Updated withdrawal epoch calculation for forger.
=> Fixed issue with different fee payments.

README.md, doc/index.md, doc/release/0.8.0.md, doc/release/eon_1.0.0.md
Added release notes in md format
Can be seen here:
https://github.com/HorizenOfficial/Sidechains-SDK/blob/is/release_notes/doc/index.md
[SDK-1393](https://horizenlabs.atlassian.net/browse/SDK-1393)
Added release notes in md format
[SDK-1393]: https://horizenlabs.atlassian.net/browse/SDK-1393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Public release notes

.gitignore, README.md, ci/run_sc.sh, examples/README.md, examples/account/evmapp/pom.xml, examples/account/evmapp_sctool/pom.xml, examples/mc_sc_workflow_example.md, examples/utxo/simpleapp/pom.xml, examples/utxo/utxoapp_sctool/pom.xml, pom.xml, qa/SidechainTestFramework/scutil.py, qa/run_sc_tests.sh, sdk/pom.xml, tools/dbtool/pom.xml, tools/sctool/pom.xml, tools/sidechains-sdk-account_sctools/pom.xml, tools/sidechains-sdk-utxo_sctools/pom.xml, tools/signingtool/pom.xml
=> bump version to 0.8.0 final

qa/sc_node_response_along_sync.py
Refactoring of sc_node_response_along_sync test  to avoid false negative
=> refactorization  to avoid false negative test

CHANGELOG.md, qa/sc_evm_gasPrice.py, sdk/src/main/scala/io/horizen/account/api/rpc/service/Backend.scala, sdk/src/test/scala/io/horizen/account/api/rpc/service/BackendTest.scala, sdk/src/test/scala/io/horizen/account/api/rpc/service/EthServiceTest.scala, sdk/src/test/scala/io/horizen/api/http/route/SidechainApplicationApiRouteTest.scala
update on eth_gasPrice ported to dev (0.9.0) branch
=> 0.8.1 to dev

sdk/src/main/scala/io/horizen/account/state/ForgerStakeMsgProcessor.scala, sdk/src/test/scala/io/horizen/forger/ForgerGenerationRateTest.scala
Reintroduced old (incorrect) method signature for the moment
=> openStakeForgerList fix

.gitignore, README.md, ci/run_sc.sh, coverage-reports/generate_report.sh, examples/README.md, examples/account/evmapp/pom.xml, examples/account/evmapp_sctool/pom.xml, examples/mc_sc_workflow_example.md, examples/utxo/simpleapp/pom.xml, examples/utxo/utxoapp_sctool/pom.xml, pom.xml, qa/SidechainTestFramework/scutil.py, sdk/pom.xml, tools/dbtool/pom.xml, tools/sctool/pom.xml, tools/sidechains-sdk-account_sctools/pom.xml, tools/sidechains-sdk-utxo_sctools/pom.xml, tools/signingtool/pom.xml
<Description of the pull request>
[<Ticket Number>](<Ticket Url>)
<Changes made> 
<Please remember to mention anyone that may be affected by these changes so that they are aware of this PR>
- <@...>
=> bump version to 0.9.0

CHANGELOG.md, README.md, ci/run_sc.sh, doc/index.md, doc/release/0.10.0.md, examples/README.md, examples/account/evmapp/pom.xml, examples/account/evmapp_sctool/pom.xml, examples/mc_sc_workflow_example.md, examples/utxo/simpleapp/pom.xml, examples/utxo/utxoapp_sctool/pom.xml, pom.xml, qa/SidechainTestFramework/scutil.py, sdk/pom.xml, tools/dbtool/pom.xml, tools/sctool/pom.xml, tools/sidechains-sdk-account_sctools/pom.xml, tools/sidechains-sdk-utxo_sctools/pom.xml, tools/signingtool/pom.xml
bump dev version to 0.10.0 snapshot
=> version 0.10.0 snapshot

CHANGELOG.md, doc/release/0.10.0.md, sdk/src/main/scala/io/horizen/account/api/rpc/service/Backend.scala, sdk/src/test/scala/io/horizen/account/api/rpc/service/BackendTest.scala
eth_gasPrice: lower percentile from 40 to 20
https://horizenlabs.atlassian.net/browse/SDK-1659
=> eth_gasPrice percentile to 20

CHANGELOG.md, README.md, ci/run_sc.sh, doc/release/0.10.0.md, examples/README.md, examples/account/evmapp/pom.xml, examples/account/evmapp_sctool/pom.xml, examples/mc_sc_workflow_example.md, examples/utxo/simpleapp/pom.xml, examples/utxo/utxoapp_sctool/pom.xml, pom.xml, qa/SidechainTestFramework/scutil.py, sdk/pom.xml, tools/dbtool/pom.xml, tools/sctool/pom.xml, tools/sidechains-sdk-account_sctools/pom.xml, tools/sidechains-sdk-utxo_sctools/pom.xml, tools/signingtool/pom.xml
changed pom version + fixed changelog
=> 0.10.0 official

CHANGELOG.md, qa/SidechainTestFramework/account/smart_contract_resources/package.json, qa/SidechainTestFramework/account/smart_contract_resources/yarn.lock, qa/truffle/package-lock.json, qa/truffle/package.json, sdk/README.md, sdk/pom.xml, sdk/src/test/scala/io/horizen/account/api/http/route/AccountEthRpcRouteTest.scala
REQUIRES NEW SPARKZ VERSION WITH https://github.com/HorizenOfficial/Sparkz/pull/79
=> SDK-1604 update vulnerable dependencies

sdk/src/test/scala/io/horizen/account/state/McAddrOwnershipMsgProcessorMultisigTest.scala
Fix for new `setupAccessList` signature.
=> Fix for new libevm

sdk/src/main/scala/io/horizen/account/api/rpc/service/EthService.scala
Wrong error returned by eth_getLogs with some block tags
[SDK-1657](https://horizenlabs.atlassian.net/browse/SDK-1657)
[SDK-1657]: https://horizenlabs.atlassian.net/browse/SDK-1657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> pc/eth_getLogs_fix  - additional eth_getLogs  parameters check

CHANGELOG.md, doc/release/0.11.0.md, qa/SidechainTestFramework/account/smart_contract_resources/contracts/ForgerStakes.sol, qa/sc_evm_forger.py, qa/sc_evm_forger_stakes_pager.py, qa/sc_evm_forger_v2.py, qa/sc_evm_forging_fee_payments.py, sdk/src/main/scala/io/horizen/account/api/http/route/AccountTransactionApiRoute.scala, sdk/src/main/scala/io/horizen/account/state/ForgerStakeMsgProcessor.scala, sdk/src/main/scala/io/horizen/account/state/ForgerStakeMsgProcessorData.scala, sdk/src/test/scala/io/horizen/account/state/ForgerStakeMsgProcessorTest.scala
Fix on getPagedForgersStakes  and getPagedForgersStakesByUser
- startIndex and pageSize are now Int32 instead of Uint32 both in input and output
- output outermost element is now a StaticStruct instead of DynamicStruct
- fixed some tests
[[<Ticket Number>](<Ticket Url>)](https://horizenlabs.atlassian.net/browse/SDK-1721)
=> getPagedForgersStakes fix on input and output types

CHANGELOG.md, doc/release/0.11.0.md
=> Version 1.3 updated changelog

sdk/src/main/scala/io/horizen/account/forger/AccountForgeMessageBuilder.scala, sdk/src/main/scala/io/horizen/account/state/AccountState.scala, sdk/src/main/scala/io/horizen/state/BaseStateReader.scala, sdk/src/test/scala/io/horizen/account/state/AccountStateViewTest.scala
Changed default forger pool distribution cap from Long.MaxValue to MAX_MONEY_IN_WEI
=> Fix distribution max cap default value

CHANGELOG.md, sdk/pom.xml
=> updated sparkz version

examples/account/evmapp/src/main/resources/sc_evm_settings.conf, sdk/src/main/java/io/horizen/metrics/MetricsManager.java, sdk/src/main/resources/sidechain-sdk-settings.conf, sdk/src/main/scala/io/horizen/AbstractSidechainApp.scala, sdk/src/main/scala/io/horizen/SidechainSettings.scala, sdk/src/main/scala/io/horizen/SidechainSettingsReader.scala, sdk/src/main/scala/io/horizen/account/AccountSidechainApp.scala, sdk/src/main/scala/io/horizen/account/api/http/route/AccountMetricsRoute.scala, sdk/src/main/scala/io/horizen/utxo/SidechainApp.scala
Metrics part 2:
- added info metric  about node version
- endpoint exposed on a separate port
- separate config values to  (optionally) specify the port and the authorization key 
[SDK-1793](https://horizenlabs.atlassian.net/browse/SDK-1793)
[SDK-1793]: https://horizenlabs.atlassian.net/browse/SDK-1793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Metrics - part 2

examples/account/evmapp/src/main/resources/sc_evm_settings.conf, sdk/pom.xml, sdk/src/main/java/io/horizen/metrics/MetricsHelp.java, sdk/src/main/java/io/horizen/metrics/MetricsManager.java, sdk/src/main/resources/sidechain-sdk-settings.conf, sdk/src/main/scala/io/horizen/AbstractSidechainApp.scala, sdk/src/main/scala/io/horizen/AbstractSidechainNodeViewHolder.scala, sdk/src/main/scala/io/horizen/SidechainSettings.scala, sdk/src/main/scala/io/horizen/SidechainSettingsReader.scala, sdk/src/main/scala/io/horizen/account/AccountSidechainApp.scala, sdk/src/main/scala/io/horizen/account/api/http/route/AccountMetricsRoute.scala, sdk/src/main/scala/io/horizen/account/forger/AccountForgeMessageBuilder.scala, sdk/src/main/scala/io/horizen/forge/AbstractForgeMessageBuilder.scala, sdk/src/main/scala/io/horizen/forge/AbstractForger.scala, sdk/src/main/scala/io/horizen/utxo/SidechainApp.scala, sdk/src/test/scala/io/horizen/account/AccountSidechainNodeViewHolderEventTest.scala, sdk/src/test/scala/io/horizen/account/AccountSidechainNodeViewHolderTest.scala, sdk/src/test/scala/io/horizen/account/forger/AccountForgeMessageBuilderTest.scala, sdk/src/test/scala/io/horizen/utxo/SidechainNodeViewHolderTest.scala, sdk/src/test/scala/io/horizen/utxo/forge/ForgerTest.scala
=> Metrics - feature branch

CHANGELOG.md, doc/release/0.12.0.md, sdk/src/main/resources/account/api/accountApi.yaml
Prepare 0.12 final on-project documentation:
- changelog
- release notes
-  yaml
[SDK-1803](https://horizenlabs.atlassian.net/browse/SDK-1803)
[SDK-1803]: https://horizenlabs.atlassian.net/browse/SDK-1803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 0.12.0 release notes & docs

qa/SidechainTestFramework/account/smart_contract_resources/contracts/ForgerStakesV2.sol, qa/sc_evm_native_forger_v2.py, sdk/src/main/scala/io/horizen/account/state/ForgerStakeV2MsgProcessor.scala, sdk/src/main/scala/io/horizen/account/state/nativescdata/forgerstakev2/StakeStartCmdInputDecoder.scala, sdk/src/main/scala/io/horizen/account/state/nativescdata/forgerstakev2/StakeStartCmdOutput.scala, sdk/src/main/scala/io/horizen/account/state/nativescdata/forgerstakev2/StakeStorage.scala, sdk/src/test/scala/io/horizen/account/state/ForgerStakeV2MsgProcessorTest.scala, sdk/src/test/scala/io/horizen/account/state/nativescdata/forgerstakev2/StakeStorageTest.scala
stakeStart native method
[SDK-1804](https://horizenlabs.atlassian.net/browse/SDK-1804)
[SDK-1804]: https://horizenlabs.atlassian.net/browse/SDK-1804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> stakeStart() native

qa/sc_evm_native_forger_v2.py, sdk/src/main/resources/account/api/accountApi.yaml, sdk/src/main/scala/io/horizen/account/api/http/route/AccountTransactionApiRoute.scala
Disabled pagedForgingStakes http API after Forger stakes V2 activaation.
[EON-1852](https://horizenlabs.atlassian.net/browse/EON-1852?atlOrigin=eyJpIjoiMDU3NzVmNjY1YjExNDhmNjk4NjEzZmVkODkzZmYwYTYiLCJwIjoiaiJ9)
[EON-1852]: https://horizenlabs.atlassian.net/browse/EON-1852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Disabled pagedForgingStakes API after Forger Stakes V2 activation

qa/sc_evm_forging_fee_payments.py, sdk/pom.xml, sdk/src/main/java/io/horizen/account/api/rpc/types/FeePaymentsView.java, sdk/src/main/java/io/horizen/account/serialization/EthJsonMapper.java, sdk/src/main/resources/account/rpc/api/eth_openrpc.json, sdk/src/test/scala/io/horizen/account/api/rpc/service/EthServiceTest.scala
https://horizenlabs.atlassian.net/browse/EON-1883
=> zen_getFeePayments should display separately the rewards from the mainchain
