HorizenOfficial/Sidechains-SDK

examples/simpleapp/README.md
examples/simpleapp/mc_sc_workflow_example.md
examples/simpleapp/pom.xml
examples/simpleapp/src/main/java/com/horizen/examples/SimpleAppModule.java
pom.xml
qa/SidechainTestFramework/sc_test_framework.py
qa/SidechainTestFramework/scutil.py
sdk/pom.xml
sdk/src/main/java/com/horizen/helper/NodeViewHelper.java
sdk/src/main/java/com/horizen/helper/TransactionSubmitHelper.java
sdk/src/main/scala/com/horizen/SidechainApp.scala
sdk/src/main/scala/com/horizen/SidechainAppModule.scala
sdk/src/main/scala/com/horizen/companion/SidechainBoxesDataCompanion.scala
sdk/src/main/scala/com/horizen/companion/SidechainProofsCompanion.scala
sdk/src/main/scala/com/horizen/companion/SidechainTransactionsCompanion.scala
sdk/src/main/scala/com/horizen/helper/NodeViewHelperImpl.scala
sdk/src/main/scala/com/horizen/helper/NodeViewProvider.scala
sdk/src/main/scala/com/horizen/helper/NodeViewProviderImpl.scala
sdk/src/main/scala/com/horizen/helper/TransactionSubmitHelperImpl.scala
sdk/src/main/scala/com/horizen/helper/TransactionSubmitProvider.scala
sdk/src/main/scala/com/horizen/helper/TransactionSubmitProviderImpl.scala
tools/sctool/pom.xml

added the 2 helpers requested by the issue, and made also these changes (after a sync with Algaro):
- added a "default" sidechain guice module which must be overridden by custom app module
- removed the inner ijector in SidechainApp  and added little more injection inside SidechainApp   (could be greater but would require a more heavy code-refactoring)
Note: I started the branch from the master branch and not  "dev" because I needed it urgently for Celsius and wanted to be based on a more  "stable" version

issue 233: add helpers for submit tx to mempool and retrieve the NodeView

---

CHANGELOG.md
README.md
ci/run_sc.sh
examples/simpleapp/README.md
examples/simpleapp/mc_sc_workflow_example.md
examples/simpleapp/pom.xml
pom.xml
qa/SidechainTestFramework/sc_test_framework.py
qa/SidechainTestFramework/scutil.py
qa/run_sc_tests.py
qa/sc_withdrawal_epoch_last_block.py
sdk/pom.xml
sdk/src/main/java/com/horizen/proof/AbstractSignature25519.java
sdk/src/main/scala/com/horizen/block/SidechainBlock.scala
sdk/src/main/scala/com/horizen/validation/WithdrawalEpochValidator.scala
sdk/src/test/scala/com/horizen/fixtures/MainchainBlockReferenceFixture.scala
sdk/src/test/scala/com/horizen/validation/WithdrawalEpochValidatorTest.scala
tools/sctool/pom.xml

Allow to have MC2ScAggTx in the last bock of the withdrawal epoch.
Previously the SC block was wrongly rejected by the validator.

WithdrawalEpochValidator fix

---

qa/run_sc_tests.py
qa/sc_cert_submitter_after_sync_1.py
qa/sc_cert_submitter_after_sync_2.py
sdk/src/main/scala/com/horizen/certificatesubmitter/CertificateSubmitter.scala

Prevent the long time await for the `getMessageToSign` results on `CertificateSubmitter`, while the internal call failed in the NVH actor thread. That decrease significantly the time of the `CertificateSubmitter` actor message queue processing after the sync is over.
Note: old utxo tree root records are removed from the state storage.
We still have a lot of warnings appeared in the log file. But they should not have an impact on the `CertificateSubmitter` logic after the sync is complete. Further improvements are needed to reduce the amount of warnings.

CertificateSubmitter: on active sync improvement

---

sdk/src/test/scala/com/horizen/SidechainMemoryPoolTest.scala

The issue was that the transaction that we expected to include in the mempool sometimes had different size to the transaction that we expected to remove (252 compared to 250) even if they were constructed in the same way (probably due to the zig zag encoding). For this reason the new transaction wasn't included in the mempool and the test was failing.
After the fix i have runned 500 times the test and it worked fine every time.

[SDK-233] Fixed putWithLimitedPoolSize() unit test

---

tools/sctool/src/main/java/com/horizen/ScBootstrappingToolCommandProcessor.java

Fixed typo in the tgenerateCertProofInfo command description.

Fixed typo in command description.

---

evm/src/main/java/com/horizen/evm/LibEvm.java
evm/src/main/java/com/horizen/evm/LibEvmLogCallback.java

- moved everything log related to separate singleton class `LibEvmLogCallback`
- this prevents the libevm log callback from being garbage collected, because previously the only reference was held by native code (which the JVM does not know or care about)

fix libevm log callback

---

libevm/pom.xml

- add libevm `build` goal to mavens `generate-resources` phase
- this will make sure the libevm binary is built not just on `package` but also on `compile`, `test`, etc.

libevm build on maven test

---

qa/sc_evm_forward_transfer.py
sdk/src/main/scala/com/horizen/account/state/AccountStateView.scala

- prevent balance changes by forward transfers to non-EOA accounts
- add TODO that we want to return the amount to the mcReturnAddress later
- add python test to verify that a FT to an existing smart contract account will not change the balance

Prevent FT to non-EOA account

---

qa/SidechainTestFramework/sc_boostrap_info.py
qa/SidechainTestFramework/scutil.py
qa/httpCalls/transaction/openStake.py
qa/httpCalls/transaction/sendCoinsToAddress.py
qa/httpCalls/transaction/sendTransaction.py
qa/sc_closed_forger.py
sdk/src/main/java/com/horizen/transaction/CoreTransactionsIdsEnum.java
sdk/src/main/java/com/horizen/transaction/OpenStakeTransaction.java
sdk/src/main/java/com/horizen/transaction/OpenStakeTransactionIncompatibilityChecker.java
sdk/src/main/java/com/horizen/transaction/OpenStakeTransactionSerializer.java
sdk/src/main/scala/com/horizen/SidechainState.scala
sdk/src/main/scala/com/horizen/api/http/SidechainTransactionApiRoute.scala
sdk/src/main/scala/com/horizen/companion/SidechainTransactionsCompanion.scala
sdk/src/main/scala/com/horizen/forge/ForgerList.scala
sdk/src/main/scala/com/horizen/fork/BaseConsensusEpochFork.scala
sdk/src/main/scala/com/horizen/fork/SidechainFork1.scala
sdk/src/main/scala/com/horizen/storage/SidechainStateStorage.scala
sdk/src/test/scala/com/horizen/SidechainStateTest.scala
sdk/src/test/scala/com/horizen/integration/SidechainStateIntegrationTest.scala
sdk/src/test/scala/com/horizen/integration/storage/SidechainStateStorageTest.scala
sdk/src/test/scala/com/horizen/storage/SidechainStateStorageTest.scala

At the moment we have the possibility to restrict the forging operation to a predefined list of forgers.
This PR includes the possibility to open the forging operation that is previously closed, to the world.
[431](https://horizenlabs.atlassian.net/jira/software/c/projects/SCHAINS/boards/3?modal=detail&selectedIssue=SCHAINS-431)
- Added new transaction type **OpenStakeTransaction**
- Added new endpoint **createOpenStakeTransaction**
- Added new endpoint **createOpenStakeTransactionSimplified**
- Non backward compatible changes in the consensus.
- Non backward compatible changes in the consensus.
- [✔] Project Builds
- [✔] Project passes tests and checks
- [✘] Updated documentation accordingly
- [✔] Breaking changes have been correctly tagged and notified

Mo/schains 431 - OpenStakeTransaction

---

sdk/src/main/resources/log4j2.xml
sdk/src/main/scala/com/horizen/SidechainApp.scala
sdk/src/main/scala/com/horizen/api/http/SidechainNodeApiRoute.scala

This PR fixes the issue that causes the Node to not terminate correctly in case of an unexpected shutdown.
[221](https://horizenlabs.atlassian.net/jira/software/c/projects/SDK/boards/14?modal=detail&selectedIssue=SDK-221&assignee=615f31c32f6aed0068c67291)
- Removed the preloaded Log shutdown hook and added its termination inside our shutdown thread.
- Fixed the akka actors termination.
- [✔] Project Builds
- [✔] Project passes unit tests
- [✔] Project passes integration tests (Python)
- [✘] Updated documentation accordingly

[SDK-221] Fixed Node termination in case of an unexpected shutdown

---

.run/.runConfiguration/SimpleApp.run.xml

This configuration allows developer to run SimpleApp in the IntelliJ IDEA without need to configure manually

Sdk 306 add run xml configuration for simple app

---

sdk/src/main/scala/com/horizen/SidechainHistory.scala
sdk/src/main/scala/com/horizen/chain/ActiveChain.scala
sdk/src/main/scala/com/horizen/chain/ElementsChain.scala
sdk/src/main/scala/com/horizen/storage/SidechainHistoryStorage.scala
sdk/src/test/scala/com/horizen/chain/ActiveChainTest.scala
sdk/src/test/scala/com/horizen/chain/ElementsChainTest.scala
sdk/src/test/scala/com/horizen/integration/SidechainHistoryTest.scala
sdk/src/test/scala/com/horizen/integration/storage/SidechainHistoryStorageTest.scala
sdk/src/test/scala/com/horizen/storage/SidechainHistoryStorageTest.scala

Starting from an issue observed during the synchronization of the Explorer:
`scnode | [DEBUG] 2022-08-24 08:21:39:076 +0000 [Grizzly-worker(7)] com.horizen.websocket.server.WebSocketServerEndpoint - Error inside GET_NEW_BLOCK_HASHES websocket request: java. lang.Exception: java.util.concurrent.TimeoutException: Futures timed out after [5000 milliseconds]`
I've discovered that the function **chainAfter** was not optimized and it did scan the entire blockchain from a starting block height to the actual tip.
This means that when the explorer wants to sync the blockchain from scratch, this function iterate from the genesis block to the tip and this was not performed in time (5 seconds) and doesn't scale with the growth of the blockchain.
In order to solve this I've added an additional …

[SDK-354] Optimized chainAfter method

---

libevm/lib/service_state.go
libevm/lib/service_state_refund.go
libevm/lib/service_state_refund_test.go

The EVM tracks gas refunds within the implementation of the SSTORE op-code, our fake smart contracts access StateDB directly and therefore bypass this logic.
This PR replicates the gas refund mechanic of SSTORE in our methods that write to account storage.

Gas refunds for fake contracts

---

sdk/src/main/scala/com/horizen/account/state/AccountStateView.scala
sdk/src/main/scala/com/horizen/account/state/AccountStateViewGasTracked.scala
sdk/src/main/scala/com/horizen/account/state/BaseAccountStateView.scala
sdk/src/main/scala/com/horizen/account/state/ForgerStakeMsgProcessor.scala
sdk/src/main/scala/com/horizen/account/state/WithdrawalMsgProcessor.scala
sdk/src/test/scala/com/horizen/account/state/ForgerStakeMsgProcessorTest.scala
sdk/src/test/scala/com/horizen/account/state/MessageProcessorFixture.scala
sdk/src/test/scala/com/horizen/account/state/WithdrawalMsgProcessorTest.scala

- remove `OutOfGas` exceptions from `BaseAccountStateView`
- remove automatic gas consumption from `AccountStateView`
- create a "gas tracked" wrapper around `BaseAccountStateView` that Message Processors can use to automatically consume gas
- reenable and fix gas verification in tests
Note: This PR requires a rebase before merge, currently it would merge into the temporary branch of #529

Automatic gas consumption for fake contracts

---

sdk/src/main/java/com/horizen/account/api/rpc/types/EthereumReceiptView.java
sdk/src/main/scala/com/horizen/account/receipt/EthereumConsensusDataReceipt.scala
sdk/src/main/scala/com/horizen/account/receipt/EthereumReceipt.scala
sdk/src/main/scala/com/horizen/account/receipt/LogsBloom.scala
sdk/src/test/scala/com/horizen/account/receipt/EthereumConsensusDataReceiptTest.scala
sdk/src/test/scala/com/horizen/account/receipt/EthereumReceiptTest.scala
sdk/src/test/scala/com/horizen/account/receipt/LogsBloomTest.scala
sdk/src/test/scala/com/horizen/account/receipt/ReceiptFixture.scala

Functions: 
- getBloomFilterValues - takes in an array of bytes, eg. a topic and returns byte indexes and values that the bytes should be set to in the bloom filter.
- addDataToBloomFilter - takes in a bloom filter instance and data, eg. a topic and returns a modified bloom filter array of bytes
- createBloomFilter - initializes an empty 256 size byte array and populates it based on the addresses from topics and topic data

Bloom filter implementation

---

sdk/src/main/java/com/horizen/account/api/rpc/types/ForwardTransfersView.java
sdk/src/main/java/com/horizen/account/api/rpc/utils/RpcError.java
sdk/src/main/scala/com/horizen/account/api/rpc/service/EthService.scala
sdk/src/main/scala/com/horizen/account/utils/AccountForwardTransfersHelper.scala

- Fixed a potential issue in `eth_getForwardTransfers` because the `match` clause was not exhaustive.
- Refactored `getBlockIdByTag` to always throw an `RpcException` with `InvalidParams` when parsing of the input fails or the given block does not exist. Previously this could throw other exceptions which would get returned to the caller as "internal error"
- Some refactoring to reduce usage of `asScala` etc.
**Note**: This does change the behavior of some RPC methods slightly. E.g. `getBalance(address, tag)` would previously return `null` in case an invalid block number is given, now it returns an "invalid params" error. To me this seems more accurate, but we need to check what the expected behavior is.
**Note 2**: This PR currently merges into `jb/truffle-fixes` becase it is based on …

RPC error updates

---

evm/src/main/java/com/horizen/evm/utils/Hash.java
qa/run_sc_tests.sh
qa/sc_evm_rpc_invalid_txs.py
sdk/src/main/java/com/horizen/account/api/rpc/types/Quantity.java
sdk/src/main/java/com/horizen/account/utils/EthereumTransactionDecoder.java
sdk/src/main/java/com/horizen/account/utils/EthereumTransactionUtils.java
sdk/src/main/java/com/horizen/utils/Utils.java
sdk/src/main/scala/com/horizen/account/api/rpc/service/EthService.scala
sdk/src/main/scala/com/horizen/account/block/AccountBlockHeader.scala
sdk/src/main/scala/com/horizen/account/forger/AccountForgeMessageBuilder.scala
sdk/src/main/scala/com/horizen/account/state/AccountStateView.scala
sdk/src/main/scala/com/horizen/account/state/ForgerStakeMsgProcessor.scala
sdk/src/main/scala/com/horizen/account/state/GasPool.scala
sdk/src/main/scala/com/horizen/account/state/StateTransition.scala
sdk/src/main/scala/com/horizen/account/state/WithdrawalMsgProcessor.scala
sdk/src/main/scala/com/horizen/account/utils/AccountFeePaymentsUtils.scala
sdk/src/main/scala/com/horizen/account/utils/AccountForwardTransfersHelper.scala
sdk/src/main/scala/com/horizen/account/utils/FeeUtils.scala
sdk/src/main/scala/com/horizen/account/utils/ZenWeiConverter.scala
sdk/src/main/scala/com/horizen/account/validation/BaseFeeBlockValidator.scala
sdk/src/test/java/com/horizen/account/transaction/EthereumTransactionTest.java
sdk/src/test/scala/com/horizen/account/forger/AccountForgeMessageBuilderTest.scala
sdk/src/test/scala/com/horizen/account/state/AccountStateTest.scala
sdk/src/test/scala/com/horizen/account/state/ForgerStakeMsgProcessorTest.scala
sdk/src/test/scala/com/horizen/account/utils/FeeUtilsTest.scala

- refactor `BigInteger` usages:
- `compareTo(BigInteger.Zero)` => `signum()` same result, better performance
- `longValue()` => `longValueExact()` make sure we throw an exception instead of working with unexpected values
- `intValue()` => `intValueExact()` same
- refactor base fee calculation
- add more test cases to make sure the edge cases are covered
- cleanup RPC methods

Refactoring

---

evm/src/main/java/com/horizen/evm/LibEvm.java
evm/src/main/java/com/horizen/evm/StateDB.java
evm/src/main/java/com/horizen/evm/interop/EvmLog.java
evm/src/main/java/com/horizen/evm/interop/ProofAccountResult.java
evm/src/main/java/com/horizen/evm/interop/ProofParams.java
evm/src/test/java/com/horizen/evm/interop/EvmLogTest.java
libevm/lib/geth_internal/proof.go
libevm/lib/service_state.go
qa/SidechainTestFramework/account/requirements.txt
qa/SidechainTestFramework/scutil.py
qa/sc_evm_backward_transfer.py
qa/sc_evm_backward_transfer_2.py
qa/sc_evm_bwt_corner_cases.py
qa/sc_evm_closed_forger.py
qa/sc_evm_eoa2eoa.py
qa/sc_evm_forger.py
qa/sc_evm_forging_fee_payments.py
qa/sc_evm_rpc_invalid_txs.py
sdk/src/main/java/com/horizen/account/api/rpc/types/Quantity.java
sdk/src/main/scala/com/horizen/account/api/rpc/service/EthService.scala
sdk/src/main/scala/com/horizen/account/state/AccountStateView.scala

Implements additional RPC functions:
- eth_getBlockTransactionCountByHash
- eth_getBlockTransactionCountByNumber
- eth_getTransactionByBlockHashAndIndex
- eth_getTransactionByBlockNumberAndIndex
- eth_getStorageAt
- eth_getProof
Also fix python test issues related to missing `0x` hex prefixes when calling RPC apis.

Additional RPC functions

---

sdk/src/main/java/com/horizen/account/api/rpc/utils/RpcCode.java
sdk/src/main/scala/com/horizen/account/api/rpc/service/EthService.scala

This seems to be the correct behavior in comparison to ethereum as this is the output from ethereum testnet using Remix IDE:

estimateGas revert error response

---

sdk/src/main/scala/com/horizen/account/state/ForgerStakeMsgProcessor.scala
sdk/src/main/scala/com/horizen/account/state/WithdrawalMsgProcessor.scala
sdk/src/test/scala/com/horizen/account/state/ForgerStakeMsgProcessorTest.scala
sdk/src/test/scala/com/horizen/account/state/WithdrawalMsgProcessorTest.scala

Reject calling view methods of fake smart contracts with msg.value greater than 0

Reject non-zero values when calling fake contract view methods

---

sdk/src/main/java/com/horizen/account/api/rpc/request/RpcId.java
sdk/src/main/java/com/horizen/account/api/rpc/request/RpcRequest.java
sdk/src/main/java/com/horizen/account/api/rpc/response/RpcResponse.java
sdk/src/main/java/com/horizen/account/api/rpc/response/RpcResponseError.java
sdk/src/main/java/com/horizen/account/api/rpc/response/RpcResponseSuccess.java
sdk/src/main/scala/com/horizen/serialization/RpcIdSerializer.scala

In this pull request the datatype the id rpc request and response was modified to long (instead of String) to be compliant with the web3.js library

EVM-405 - rpc id numeric datatype

---

qa/SidechainTestFramework/scutil.py
sdk/src/main/scala/com/horizen/SidechainNodeViewHolder.scala
sdk/src/test/scala/com/horizen/SidechainStateTest.scala
sdk/src/test/scala/com/horizen/fixtures/BoxFixture.scala

Fixed maxBTsPerBlockTest unit test.
Removed unused LocallyGeneratedTransaction from SidechainNodeViewHolder.
Fixed default sidechain dir initialization in Python test framework. It fixed sc_nodes_initialize.py and sc_node_api_test.py tests.

Minor bugfixes(SDK-464, SDK-369)

---

sdk/src/main/java/com/horizen/account/api/rpc/service/RpcService.java
sdk/src/main/java/com/horizen/account/api/rpc/types/EthereumBlock.java

- fix internal error when RPC request does not contain the `params` property
- treat it like `params: []`
- fix strict RPC clients falling over our "empty" block nonce `0x`
- explicitly set it to 8 bytes (16 hex chars ) of zeroes `0x0000000000000000`
- GETH otherwise throws: `hex string has length 0, want 16 for BlockNonce`

fix RPC issues

---

sdk/src/main/scala/com/horizen/account/api/rpc/service/EthService.scala
sdk/src/test/scala/com/horizen/account/api/http/AccountEthRpcRouteTest.scala

implementation of the following rpc methods:
- eth_getUncleCountByBlockHash
- eth_getUncleCountByBlockNumber
- eth_getUncleByBlockHashAndIndex
- eth_getUncleByBlockNumberAndIndex

eth_getUncle: rpc methods implementation

---

qa/sc_backward_transfer.py
qa/sc_bwt_minimum_value.py
qa/sc_cert_key_rotation.py
qa/sc_cert_key_rotation_across_epoch.py
qa/sc_cert_key_rotation_old_circuit.py
qa/sc_cert_submission_decentralization.py
qa/sc_csw_disabled.py
qa/sc_genesisinfo_sc_versions.py
qa/sc_multiple_pending_certs_non_ceasing.py
qa/sc_versions_and_mc_certs.py
sdk/src/main/java/com/horizen/cryptolibprovider/implementations/SchnorrFunctionsImplZendoo.java
sdk/src/main/java/com/horizen/cryptolibprovider/utils/SchnorrFunctions.java
sdk/src/main/java/com/horizen/proposition/SchnorrProposition.java
sdk/src/main/resources/api/sidechainApi.yaml
sdk/src/main/scala/com/horizen/SidechainState.scala
sdk/src/main/scala/com/horizen/api/http/SidechainSubmitterApiRoute.scala
sdk/src/main/scala/com/horizen/block/MainchainBlockReference.scala
sdk/src/main/scala/com/horizen/block/MainchainBlockReferenceData.scala
sdk/src/main/scala/com/horizen/block/SidechainBlock.scala
sdk/src/main/scala/com/horizen/certificatesubmitter/strategies/CircuitStrategy.scala
sdk/src/main/scala/com/horizen/certificatesubmitter/strategies/WithKeyRotationCircuitStrategy.scala
sdk/src/main/scala/com/horizen/certificatesubmitter/strategies/WithoutKeyRotationCircuitStrategy.scala
sdk/src/main/scala/com/horizen/storage/SidechainStateStorage.scala
sdk/src/test/scala/com/horizen/SidechainStateTest.scala
sdk/src/test/scala/com/horizen/SidechainWalletCswDataProviderCSWEnabledTest.scala
sdk/src/test/scala/com/horizen/block/MainchainBlockReferenceTest.scala
sdk/src/test/scala/com/horizen/fixtures/MainchainBlockReferenceFixture.scala
sdk/src/test/scala/com/horizen/integration/SidechainStateIntegrationTest.scala
sdk/src/test/scala/com/horizen/storage/SidechainStateStorageTest.scala

Non-ceasing sidechain zen 4.0.0 compatibility fixes:
1) fixing the issue with certificate rejection in case of previous certificate delay).
2) MC block ref data structure has been reverted to be identical to the ceasing case, since no more multiple certificates for different epochs are allowed.
3) memory leak fix for zendoo-sc-cryptolib
Test with MC tag `v4.0.0-rc2`

Non ceasing pending certs

---

sdk/src/main/java/com/horizen/account/api/rpc/types/EthereumReceiptView.java

The `to` and `contractAddress` fields will always be included in the `eth_getTransactionReceipt` rpc method response

EVM-626 - tx receipt to and contract address always included in rpc response

---

sdk/src/main/java/com/horizen/account/api/rpc/types/EthereumTransactionView.java

The `to` field will always be included in the rpc response even if null (contract creation transaction cases)

EVM-625 - transaction to field always included in rpc response

---

sdk/pom.xml
sdk/src/main/scala/com/horizen/account/state/AccountState.scala

Fixed zendoo-sc-cryptolib dependency version to the timestamp

Non-ceasing sidechains: fix certificate validation in the account state.

---

sdk/src/main/scala/com/horizen/account/api/http/AccountTransactionApiRoute.scala
sdk/src/main/scala/com/horizen/account/state/StateDbAccountStateView.scala
sdk/src/test/scala/com/horizen/account/state/EoaMessageProcessorIntegrationTest.scala
sdk/src/test/scala/com/horizen/account/state/EoaMessageProcessorTest.scala
sdk/src/test/scala/com/horizen/account/state/EvmMessageProcessorIntegrationTest.scala
sdk/src/test/scala/com/horizen/account/state/ForgerStakeMsgProcessorTest.scala
sdk/src/test/scala/com/horizen/account/state/MessageProcessorFixture.scala
sdk/src/test/scala/com/horizen/account/state/StateDbAccountStateViewGasTrackedTest.scala
sdk/src/test/scala/com/horizen/account/state/WithdrawalMsgProcessorIntegrationTest.scala

- fixed `sc_evm_closed_forger.py` by increasing default gas limits in the http api
- fixed `NullPointerException` in  `StateDbAccountStateViewGasTracked.removeAccountStorage`
- updated gas usage in `ForgerStakeMsgProcessorTest`
- added gas usage verification to `WithdrawalMsgProcessorTest`
- updated EOA and EVM message processor tests to not use `applyMessage` but the processors `process` method directly
Tests of gas usage for the ForgerStakesMsgProcessor were using wrong numbers, because they did not reset the access list between multiple calls ("warm" account access uses less gas, etc.).

fix gas tests

---

evm/src/main/java/com/horizen/evm/LibEvmCallback.java
evm/src/main/java/com/horizen/evm/StateDB.java
evm/src/test/java/com/horizen/evm/StateDBTest.java
libevm/lib/state.go
libevm/lib/state_test.go

- update "isEoa" logic to include a check for the addresses of precompiled native contract

EVM-737 allow calling precompiled contracts

---

examples/README.md
sdk/pom.xml
sdk/src/test/scala/com/horizen/fixtures/BasicAuthenticationFixture.scala
sdk/src/test/scala/io/horizen/account/api/http/route/AccountEthRpcRouteMock.scala
sdk/src/test/scala/io/horizen/account/api/http/route/AccountSidechainApiRouteTest.scala
sdk/src/test/scala/io/horizen/api/http/route/SidechainApiRouteTest.scala
tools/sctool/pom.xml
tools/sctool/src/main/java/io/horizen/ScBootstrappingToolCommandProcessor.java

Update Bcrypt library.
[756](https://horizenlabs.atlassian.net/jira/software/c/projects/SDK/boards/14?modal=detail&selectedIssue=SDK-756&assignee=615f31c32f6aed0068c67291)
- Updated Bcrypt library inside Bootstrapping tool
- No breaking changes, the new library allows to use older version of algorithm
- [✔] Project Builds
- [✔] Project passes unit tests
- [✔] Project passes integration tests (Python)
- [✔] Updated documentation accordingly

Updated Bcrypt library

---

sdk/src/main/java/io/horizen/account/api/rpc/handler/RpcException.java
sdk/src/main/java/io/horizen/account/api/rpc/service/RpcService.java
sdk/src/main/java/io/horizen/account/api/rpc/types/FilterQuery.java
sdk/src/main/java/io/horizen/account/api/rpc/types/TransactionArgs.java
sdk/src/main/scala/io/horizen/account/api/rpc/service/EthService.scala

- refactored `TransactionArgs` and `FilterQuery` to be immutable as much as possible
- added more validation to both types
- this also fixes a `NullPointerException` caused by optional arguments being omitted, e.g. omitting `value` from an RPC call to `eth_sendTransaction`

Fix RPC parameter types

---

sdk/src/main/java/io/horizen/utils/CheckedCompanion.scala
sdk/src/main/scala/io/horizen/account/api/http/route/AccountTransactionApiRoute.scala
sdk/src/main/scala/io/horizen/account/companion/SidechainAccountTransactionsCompanion.scala
sdk/src/main/scala/io/horizen/api/http/route/BlockBaseApiRoute.scala
sdk/src/main/scala/io/horizen/api/http/route/WalletBaseApiRoute.scala
sdk/src/main/scala/io/horizen/companion/SidechainSecretsCompanion.scala
sdk/src/main/scala/io/horizen/utxo/api/http/route/SidechainTransactionApiRoute.scala
sdk/src/main/scala/io/horizen/utxo/api/http/route/SidechainWalletApiRoute.scala
sdk/src/main/scala/io/horizen/utxo/companion/SidechainBoxesCompanion.scala
sdk/src/main/scala/io/horizen/utxo/companion/SidechainTransactionsCompanion.scala
sdk/src/test/scala/io/horizen/account/api/http/route/AccountTransactionApiRouteTest.scala
sdk/src/test/scala/io/horizen/utxo/api/http/route/SidechainTransactionApiRouteTest.scala
sdk/src/test/scala/io/horizen/utxo/api/http/route/SidechainWalletApiRouteTest.scala
sdk/src/test/scala/io/horizen/utxo/companion/SidechainBoxesCompanionTest.scala
tools/signingtool/src/main/java/io/horizen/SigningToolCommandProcessor.java

Added a trait to be used by companion objects if necessary, in order to have a checked (no trailing data) byte array after the parsing.
https://horizenlabs.atlassian.net/browse/SDK-712

Truncated Trailing Data in Parsing Functions

---

sdk/pom.xml

Regression passed. New version is backward compatible to the 0.6.0-rc1

zendoo-sc-crpytolib version upgraded to 0.6.0

---

sdk/src/main/java/io/horizen/cryptolibprovider/utils/InMemorySparseMerkleTreeWrapper.java
sdk/src/test/java/io/horizen/cryptolibprovider/InMemorySparseMerkleTreeWrapperTest.java

Added height restriction for the Merkel Tree Wrapper.
Height must be not less than 0 and less or equal to 22.
Added tests to check these restrictions.

NCC. Height restriction for the Merkel Tree Wrapper.

---

sdk/src/main/java/io/horizen/account/state/ExecutionRevertedException.java
sdk/src/main/scala/io/horizen/account/api/rpc/service/EthService.scala
sdk/src/main/scala/io/horizen/account/state/StateDbAccountStateView.scala

Before:
```
[ERROR] 2023-03-30 19:24:22:674 +0300 [StateDbAccountStateView.scala:211 ] [2-Hop-akka.actor.default-dispatcher-16] io.horizen.account.state.AccountStateView - applying message failed, tx.id=3bc1b2459b8ed7608b2b50ac2db8810dc4e56d46df14a9039510b27b73a995b4
io.horizen.account.state.ExecutionRevertedException: Key Rotation Proof is invalid: Key rotation proof - master signature is invalid: 0
at io.horizen.account.state.CertificateKeyRotationMsgProcessor.execSubmitKeyRotation(CertificateKeyRotationMsgProcessor.scala:159) ~[sidechains-sdk-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
at io.horizen.account.state.CertificateKeyRotationMsgProcessor.process(CertificateKeyRotationMsgProcessor.scala:44) ~[sidechains-sdk-0.7.0-SNAPSHOT.jar:0.7.0-SNAPSHOT]
at …
```

[SDK-827] StateDbAccountStateView: failed transaction log level fixes

---

tools/sctool/src/main/java/io/horizen/ScBootstrappingToolCommandProcessor.java

Introduced maximum seed length for a key generation of all types.
Introduced minimum seed length for generatedKey and generateAccountKey.
It's safe to use generateVrfKey and generateCertificateSignerKey with an empty seed.

Evm 757 seed length

---

sdk/src/main/scala/io/horizen/AbstractSidechainNodeViewHolder.scala
sdk/src/main/scala/io/horizen/utxo/mempool/SidechainMemoryPool.scala
sdk/src/test/scala/io/horizen/fixtures/MockedSidechainNodeViewHolderFixture.scala
sdk/src/test/scala/io/horizen/fixtures/SidechainBlockFixture.scala
sdk/src/test/scala/io/horizen/fixtures/TransactionFixture.scala
sdk/src/test/scala/io/horizen/utxo/SidechainNodeViewHolderTest.scala
sdk/src/test/scala/io/horizen/utxo/mempool/SidechainMemoryPoolTest.scala

- Fixed issue of adding transaction to the full mempool. Adding transaction cause removing transaction with the lowest fee rate  but it may happen that finally this transaction won't be added. addWithSizeCheck removes transaction from mempool only after checking that new transaction can be applied.
- Overrided UpdateMempool AbstractSidechainNodeViewHolder. Earlier it added all transactions from removed blocks to the mempool and only after that filtering them with transaction from applied blocks. It also may cause removing low fee rate transaction from the full mempool.
- Added unit test for before mention cases.

Sdk-658 mempool size issues

---

qa/SidechainTestFramework/account/ac_use_smart_contract.py
qa/SidechainTestFramework/account/ac_utils.py
qa/run_sc_tests.sh
qa/sc_evm_eip_1898.py
sdk/src/main/scala/io/horizen/account/api/rpc/service/EthService.scala
sdk/src/test/scala/io/horizen/account/api/rpc/service/EthServiceTest.scala
sdk/src/test/scala/io/horizen/account/utils/AccountMockDataHelper.scala

This pull request contains the manage of the EIP-1898 input for the following RPC methods:
- `eth_getBalance`
- `eth_getStorageAt`
- `eth_getTransactionCount`
- `eth_getCode`
- `eth_call`
- `eth_getProof`
The input is managed using the `EthService.getBlockTagByEip1898` method that is able to manage both String-String map or simple String (like the old implementation). 
In case the EIP-1898 input contains the `blockHash` the method reported above will retrieve and return its related block number, afterwards the block hash is retrieved again inside the RPC method logic. This process is obviously not efficient but I decide to proceed this way to not impact the current implementation for the others RPC methods of the `EthService` that are based on methods that expect the block number or the …

SDK-912 - EIP-1898

---

sdk/src/main/java/io/horizen/account/api/rpc/types/EthereumBlockView.java
sdk/src/test/scala/io/horizen/account/api/rpc/service/EthServiceTest.scala

`extraData` and `sha3Uncles` format fixed, now they are returned with pattern 0x followed by 64 0s
Unit test updated

SDK-1027 - extraData and sha3Uncles format fix

---

sdk/src/main/scala/io/horizen/account/api/rpc/service/EthService.scala
sdk/src/test/scala/io/horizen/account/api/rpc/service/EthServiceTest.scala

Bug details in task [SDK-1070](https://horizenlabs.atlassian.net/browse/SDK-1070). The bug was due to the `return` statement of the `if (blocks < 1)` condition.
For a bit of context if we try to use a `return` statement inside a lambda function that is defined inside a method, we will get a compilation error in _Scala_ (not managed in our case). This is because the `return` statement would try to exit the enclosing method, not just the lambda function. However, in _Scala_, a lambda function is not allowed to have side-effects outside of its own body. This means that it cannot modify any variables outside of its own scope or exit the enclosing method.
To use the `return` statement a workaround might be use a named function instead of a lambda function but, in general, using `return` in …

SDK-1070 - eth_feeHistory bug fix

---

sdk/src/main/java/io/horizen/account/api/rpc/request/RpcRequest.java

Check added on jsonrpc value, it must be `2.0` as require by json rpc v2.0 specs.
Details in Jira task [SDK-1209](https://horizenlabs.atlassian.net/browse/SDK-1209).
[SDK-1209]: https://horizenlabs.atlassian.net/browse/SDK-1209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SDK-1209 - check on jsonrpc request in 

---

qa/SidechainTestFramework/account/ac_use_smart_contract.py
qa/SidechainTestFramework/account/requirements.txt

[Jira ticket](https://horizenlabs.atlassian.net/browse/SDK-1243?atlOrigin=eyJpIjoiY2I0YTgyYWIyN2NjNGE1NWJmM2UzMmVkNmVmZGViZWEiLCJwIjoiaiJ9)
Starting eth-abi version 4.0.0, methods `encode_abi` and `decode_abi` have been deprecated and are replaced by `encode` and `decode` methods respectfully. 
The tests run successfully now and requirements.txt is updated to require eth-abi>=4.0.0

SDK-1243 - upgrade eth-abi to the latest package

---

CHANGELOG.md
README.md
examples/simpleapp/README.md
examples/simpleapp/mc_sc_workflow_example.md
examples/simpleapp/pom.xml
pom.xml
qa/SidechainTestFramework/sc_test_framework.py
qa/SidechainTestFramework/scutil.py
qa/SidechainTestFramework/secure_enclave_http_api_server.py
sdk/pom.xml
tools/dbtool/pom.xml
tools/sctool/pom.xml
tools/signingtool/pom.xml

0.6.1 will be released to fix a pom issue in the 0.6.0 (zendoo-sc-cryptolib refferd there was a snapshot version no more present on maven central)
(0.6.0 was never relesed officially but was published in maven central, thus we can't update it)
This version wil be released together with the 0.7.0 (used in EON)

0.6.1 final

---

qa/run_sc_tests.sh
qa/sc_evm_feeHistory.py
sdk/src/main/scala/io/horizen/account/api/rpc/service/EthService.scala
sdk/src/test/scala/io/horizen/account/api/rpc/service/EthServiceTest.scala

[Jira ticket](https://horizenlabs.atlassian.net/browse/SDK-1150?atlOrigin=eyJpIjoiYWViZTAwOWUwNDlhNGMxNmFjYjM1ZDkxNTM5YTBlOGMiLCJwIjoiaiJ9)
I discovered that the error happens in [this](https://github.com/HorizenOfficial/Sidechains-SDK/blob/04676955c2e918ab3f0f08c5fa74b47d58c1b251/sdk/src/main/scala/io/horizen/account/api/rpc/service/EthService.scala#LL1020C15-L1020C48) line when the height parameter is greater than the current SC height which always happens in the last iteration when input block tag is pending.  As a result, a block is null and `NullPointerException` happens when we try to access the block header. My proposed solution includes block null check and in the last iteration uses previously computed `requestedBlock` which contains information on pending block.

SDK-1150 - eth_feeHistory pending block tag fix

---

sdk/src/main/scala/io/horizen/account/api/rpc/service/EthService.scala

traceTrancastion can be called for a eoa2eoa transaction, that is not processed by EvmMessageProcessor, so there's no trace to return.
https://horizenlabs.atlassian.net/browse/SDK-1282
Adds a null check before getting tracerResult

check for NPE in calls that expect tracerResult from evm

---

qa/SidechainTestFramework/secure_enclave_http_api_server.py
sdk/src/main/scala/io/horizen/api/http/client/SecureEnclaveApiClient.scala
sdk/src/test/scala/io/horizen/api/http/client/SecureEnclaveApiClientTest.scala

This PR is addressing a bug introduced by [this PR](https://github.com/HorizenOfficial/Sidechains-SDK/pull/841) which is adding `Content-Type` and `Accept` HTTP headers to requests in the secure enclave.
After reading the docs, it turns out it's not advisable and is redundant to add Content-Type header manually, but it is inferred from the `contentType` field in `HttpEntity`. Adding it does not result in an error but in a warning message which is what this code is addressing [[source](https://doc.akka.io/docs/akka-http/current/common/http-model.html#:~:text=from%20%E2%80%9Cregular%E2%80%9D%20headers%3A-,Content%2DType,rendered%20onto%20the%20wire%20and%20trigger%20a%20warning%20being%20logged%20instead!,-Transfer%2DEncoding)]
The warning message is  `evmapp  | …

SDK-1295 - Content-Type HTTP header fix in SecureEnclaveApiClient

---

qa/SidechainTestFramework/account/httpCalls/transaction/createKeyRotationTransaction.py
qa/sc_evm_cert_key_rotation.py
sdk/src/main/scala/io/horizen/account/api/http/route/AccountTransactionApiRoute.scala

The default gas limit for key rotation transactions increased from 42000 to 500000 after discovering that it was not enough.
Testing shows 276988 gas is used, but after discussion with @MarcoOl94 we put 500000 just to be sure that it's enough to be executed since this type of transaction is rare.
[SDK-1255](https://horizenlabs.atlassian.net/browse/SDK-1255?atlOrigin=eyJpIjoiYmI1M2Q4Mzg5ZmFjNDg2YmEzMjMzMmU3Yjc4MGEyZGIiLCJwIjoiaiJ9)
The default limit increased.
sc_evm_cert_key_rotation.py updated to include 1 key rotation transaction with default gas info.
/
[SDK-1255]: https://horizenlabs.atlassian.net/browse/SDK-1255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SDK-1255 - default gas limit for key rotation tx increased

---

sdk/src/main/scala/io/horizen/history/AbstractHistory.scala
sdk/src/test/scala/io/horizen/utxo/integration/SidechainHistoryTest.scala

On the current implementation there is a problem in the way we calculate and send `SyncInfo` to the other nodes. The other node height retrieved from the  `SyncInfo` message is not correctly estimated and this lead in some cases to consider another node more updated as younger. In this situation the node consider itself more developed and stop processing other `SyncInfo` messages remaining stuck at certain height.
With the current PR we introduced a new method to correctly calculate the other node height (method `calculateOtherNodeApproxHeight`).
The Equal return statement in case the divergent suffix sequence size is greater than one was  removed because it is currently a fork situation, an existing comment on the code reported exactly that.
details in task …

SDK-960 - avoid nodes sync indefinitely

---

sdk/pom.xml

This PR is addressing an issue where sdk `pom.xml` is generating javadocs that don't include scala files, but only java ones. The issue is fixed by deleting `maven-javadoc-plugin` and updating `scala-maven-plugin` which supports the documentation generation for both java and scala files.
[SDK-1253](https://horizenlabs.atlassian.net/browse/SDK-1253?atlOrigin=eyJpIjoiYTRiYjFhY2JmNGEzNDJkOGE0YzM3MDk5ZjA4MmM3ZjYiLCJwIjoiaiJ9)
sdk `pom.xml` updated
<Please remember to mention anyone that may be affected by these changes so that they are aware of this PR>
there shouldn't be any breaking changes, but should be double checked by @paolocappelletti 
[SDK-1253]: https://horizenlabs.atlassian.net/browse/SDK-1253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …

SDK-1253 - sdk pom.xml updated to generate javadoc including scala files

---

sdk/src/test/scala/io/horizen/api/http/route/MainchainBlockApiRouteTest.scala

Increasing the timout for bestBlockReferenceInfo api test
Added `when(mockedRESTSettings.timeout).thenReturn(5.seconds)` to increase test time
None

Increasing timeout for bestBlockReferenceInfo api test

---

sdk/src/main/scala/io/horizen/SidechainSettings.scala

We want to hide wallet **seed** string from logs
[SDK-1404](https://horizenlabs.atlassian.net/jira/software/c/projects/SDK/boards/14?modal=detail&selectedIssue=SDK-1404&assignee=615f31c32f6aed0068c67291)
[SDK-1404]: https://horizenlabs.atlassian.net/browse/SDK-1404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Hide seed string from logs

---

qa/run_sc_tests.sh
qa/sc_evm_rpc_eth.py
sdk/src/main/scala/io/horizen/account/api/rpc/service/EthService.scala
sdk/src/test/scala/io/horizen/account/api/rpc/service/EthServiceTest.scala
sdk/src/test/scala/io/horizen/account/utils/AccountMockDataHelper.scala

eth_getTransactionByHash rpc method was changed in order to retrieve also transactions still in the mempool, as it should  according to our internal documentation available on postman.
[SDK_1532](https://horizenlabs.atlassian.net/browse/SDK-1532?atlOrigin=eyJpIjoiM2Q0N2JmZDFjMGY3NDJlMmEyNDYxMDNhYTZlYTlkMWIiLCJwIjoiaiJ9)
In EthService.scala added a new method that looks for a transaction first in the History and, if not found, in the mempool.
- [ X] Project Builds
- [ X] Project passes tests and checks

Fix for SDK_1532: eth_getTransactionByHash doesn't access the mempool

---

qa/run_sc_tests.sh
qa/sc_withdrawal_certificate_after_mainchain_nodes_were_disconnected.py
sdk/src/main/scala/io/horizen/certificatesubmitter/dataproof/CertificateDataWithKeyRotation.scala

Add test to verify sidechain nodes can still create certificates when the mainchain nodes their connected to temporarily are offline
[SDK-1430](https://horizenlabs.atlassian.net/browse/SDK-1430)
Add test to verify sidechain nodes can still create certificates when the mainchain nodes their connected to temporarily are offline
No breaking changes
[SDK-1430]: https://horizenlabs.atlassian.net/browse/SDK-1430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SDK-1430: add test to verify sidechain nodes can still create certificates when mc nodes are offline

---

examples/utxo/simpleapp/src/main/java/io/horizen/examples/SimpleAppModule.java
sdk/src/main/scala/io/horizen/account/AccountSidechainApp.scala

Version 1.0.1 changed the storage versions to keep to 1 for some storages, but that was too much to support the storage recovery procedure in case of crash douring the node update.
This PR increases the minimum versions from 1 to 5.
Following tests were failing with 1 and now are ok:
sc_evm_storage_recovery.py
sc_storage_recovery_with_csw.py
sc_storage_recovery_without_csw.py

Fix min storage version for recovery

---

sdk/src/main/scala/io/horizen/account/state/AccountState.scala
sdk/src/main/scala/io/horizen/fork/ConsensusParamsFork.scala
sdk/src/test/scala/io/horizen/account/state/AccountStateTest.scala

A new test is added in `AccountStateTest.scala` which tests the epoch switch between 2 consensus forks.
[SDK-1465](https://horizenlabs.atlassian.net/browse/SDK-1465?atlOrigin=eyJpIjoiYjg2NzlmMTY3YzE4NGNkMWIwMmQxMDBjNzJmMmEyYjIiLCJwIjoiaiJ9)
Added new test `testSwitchingConsensusEpochsWith2Forks` which creates 2 consensus params forks, one with default consensus params forks (720, 12) , and another one with 100 slots in epoch and 10 seconds for each slot. The test validates that correct epochs are calculated for certain block timestamps w.r.t. active consensus params fork.
No breaking changes.
[SDK-1465]: https://horizenlabs.atlassian.net/browse/SDK-1465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SDK-1465 : New unit test for epoch switch in AccountStateTest

---

qa/sc_evm_eoa2eoa.py
sdk/src/main/scala/io/horizen/account/api/http/route/AccountTransactionApiRoute.scala

Wallet address lookup is now case insensitive in create transactions endpoints
https://horizenlabs.atlassian.net/browse/SDK-1610

pc/SDK-1610 - private key selection case insensitive

---

CHANGELOG.md
doc/release/0.10.0.md
qa/run_sc_tests.sh
sdk/src/main/scala/io/horizen/account/state/ForgerStakeMsgProcessor.scala
sdk/src/test/scala/io/horizen/account/state/ForgerStakeMsgProcessorTest.scala

Fix the signature of openStakeForgerList method, keeping retro-compatibility with old but wrong signature.
[SDK-1606](https://horizenlabs.atlassian.net/browse/SDK-1606?atlOrigin=eyJpIjoiZTgzOGRmNWJkOWVkNDdmZThkNjdkOTIxZjE0MjNiNmMiLCJwIjoiaiJ9)
Modified ForgerStakeMsgProcessor and its unit test.
- [ X] Project Builds
- [ X] Project passes tests and checks
- [X ] Updated documentation accordingly
- [ X] Breaking changes have been correctly tagged and notified
[SDK-1606]: https://horizenlabs.atlassian.net/browse/SDK-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix for wrong signature of openStakeForgerList

---

CHANGELOG.md
sdk/src/main/scala/io/horizen/SidechainSettings.scala
sdk/src/main/scala/io/horizen/account/api/rpc/service/EthService.scala
sdk/src/test/scala/io/horizen/account/api/rpc/service/EthServiceTest.scala

eth_getLogs with earliest and latest block tags timed out because it tried to inspect all the blocks. Failing EthService actor also failed all the other concurrent calls
https://horizenlabs.atlassian.net/browse/SDK-1643
Added a configurable limit of blocks that can be inspected. Limit set to 10000. Change error message to represent new condition.

Limit number of block to traverse for eth_getLogs

---

sdk/src/main/java/io/horizen/account/api/rpc/types/EthereumTransactionView.java
sdk/src/test/scala/io/horizen/account/api/rpc/service/EthServiceTest.scala

Some ETH endpoints use separate EthereumTransactionView response class, that need to be also covered with condition to re-calculate signature V field.

SDK-1687 - hotfix for signature V field in eth endpoints

---

qa/SidechainTestFramework/account/smart_contract_resources/contracts/ReceivingEther.sol
qa/SidechainTestFramework/sc_boostrap_info.py
qa/SidechainTestFramework/scutil.py
qa/resources/template.conf
qa/run_sc_tests.sh
qa/sc_evm_forger_reward_address.py
qa/sc_evm_forging_fee_payments.py
sdk/src/main/scala/io/horizen/AbstractSidechainApp.scala
sdk/src/main/scala/io/horizen/SidechainSettings.scala
sdk/src/main/scala/io/horizen/account/forger/AccountForgeMessageBuilder.scala
sdk/src/main/scala/io/horizen/params/MainNetParams.scala
sdk/src/main/scala/io/horizen/params/NetworkParams.scala
sdk/src/main/scala/io/horizen/params/RegTestParams.scala
sdk/src/main/scala/io/horizen/params/TestNetParams.scala
sdk/src/test/java/io/horizen/account/secret/McSignatureTest.java
sdk/src/test/java/io/horizen/utils/BytesUtilsTest.java
sdk/src/test/scala/io/horizen/account/forger/AccountForgeMessageBuilderTest.scala
tools/sctool/src/main/java/io/horizen/ScBootstrappingToolCommandProcessor.java

Add a config property to specify forger reward address - forging tips and rewards will be sent to that address. Does not have to owned by a forger.
https://horizenlabs.atlassian.net/browse/SDK-1635
- [] Updated documentation accordingly
- [] Breaking changes have been correctly tagged and notified

Forger reward address

---

qa/sc_evm_mc_addr_ownership.py
sdk/src/main/scala/io/horizen/account/state/McAddrOwnershipMsgProcessor.scala

Removed a redundant check on nonce in native smart contract.
Fix for issue [SDK-1575](https://horizenlabs.atlassian.net/browse/SDK-1575?atlOrigin=eyJpIjoiMDZmNWEzZjI5OTAyNGE4OWI1NjQzODNlN2M5ZTU0MjIiLCJwIjoiaiJ9)
[SDK-1575]: https://horizenlabs.atlassian.net/browse/SDK-1575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Removed a redundant check on nonce in native smart contract

---

sdk/src/main/java/io/horizen/utils/BytesUtils.java
sdk/src/test/java/io/horizen/utils/BytesUtilsTest.java

Improved the error message in case of wrong MC address type.
[SDK-1734](https://horizenlabs.atlassian.net/browse/SDK-1734?atlOrigin=eyJpIjoiOTg0ZWY5ZDQzMjVlNDY0NjlkM2JhZjQxNGYyMzVjNmIiLCJwIjoiaiJ9)
[SDK-1734]: https://horizenlabs.atlassian.net/browse/SDK-1734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improved error message for fromHorizenMcTransparentAddress method

---

qa/sc_evm_rpc_eth.py
sdk/src/main/java/io/horizen/account/api/rpc/handler/RpcResponseException.java
sdk/src/main/java/io/horizen/account/api/rpc/request/RpcRequest.java
sdk/src/main/scala/io/horizen/account/api/http/route/AccountEthRpcRejectionHandler.scala
sdk/src/main/scala/io/horizen/account/api/http/route/AccountEthRpcRoute.scala
sdk/src/main/scala/io/horizen/account/api/rpc/service/RpcProcessor.scala
sdk/src/main/scala/io/horizen/account/websocket/WebSocketAccountServerEndpoint.scala
sdk/src/main/scala/io/horizen/api/http/SidechainApiResponse.scala
sdk/src/test/scala/io/horizen/account/api/http/route/AccountEthRpcRouteTest.scala

Fixes for json-rpc:
https://horizenlabs.atlassian.net/browse/SDK-1660 (compliance with geth)
https://horizenlabs.atlassian.net/browse/SDK-1706 (compliance with standard)
The desired behavior described in SDK-1660 must be verified to be real compliance with geth and in case the fix should be reverted.

Fix for json rpc compliancy

---

qa/sc_evm_rpc_web3_methods.py
sdk/src/main/scala/io/horizen/account/AccountSidechainApp.scala
sdk/src/main/scala/io/horizen/account/api/rpc/service/RpcUtils.scala
sdk/src/main/scala/io/horizen/api/http/route/SidechainNodeApiRoute.scala
sdk/src/test/scala/io/horizen/account/fixtures/MockedRpcProcessor.scala

https://horizenlabs.atlassian.net/browse/SDK-1331
Simple change to include eon version into web3_clientVersion response instead of sdk version

SDK-1331 - web3_clientVersion should return EON version

---

examples/account/evmapp/src/main/java/io/horizen/examples/AppForkConfigurator.java
examples/account/evmapp/src/main/java/io/horizen/examples/AppForkConfiguratorAllEnabledFromEpoch2.java
qa/SidechainTestFramework/account/utils.py
qa/sc_evm_forging_fee_payments.py
sdk/src/main/scala/io/horizen/account/AccountSidechainNodeViewHolder.scala
sdk/src/main/scala/io/horizen/account/forger/AccountForgeMessageBuilder.scala
sdk/src/main/scala/io/horizen/account/fork/Version1_4_0Fork.scala
sdk/src/main/scala/io/horizen/account/state/AccountState.scala
sdk/src/main/scala/io/horizen/account/state/AccountStateView.scala
sdk/src/main/scala/io/horizen/account/utils/AccountFeePaymentsUtils.scala
sdk/src/main/scala/io/horizen/params/MainNetParams.scala
sdk/src/main/scala/io/horizen/params/NetworkParams.scala
sdk/src/main/scala/io/horizen/params/RegTestParams.scala
sdk/src/main/scala/io/horizen/params/TestNetParams.scala
sdk/src/main/scala/io/horizen/state/BaseStateReader.scala
sdk/src/test/java/io/horizen/account/secret/McSignatureTest.java
sdk/src/test/java/io/horizen/utils/BytesUtilsTest.java
sdk/src/test/scala/io/horizen/account/AccountSidechainNodeViewHolderTest.scala
sdk/src/test/scala/io/horizen/account/state/AccountStateTest.scala
sdk/src/test/scala/io/horizen/account/state/AccountStateViewTest.scala
sdk/src/test/scala/io/horizen/account/utils/AccountFeePaymentsUtilsTest.scala
sdk/src/test/scala/io/horizen/fixtures/sidechainblock/generation/SidechainBlocksGenerator.scala
sdk/src/test/scala/io/horizen/utils/TimeToEpochUtilsTest.scala
tools/sctool/src/main/java/io/horizen/ScBootstrappingToolCommandProcessor.java

Add a limit(cap) of funds from mainchain that are available for distribution at the end of withdrawal epoch.
Cap is calculated as 10% of mainchain coinbase reward from the current withdrawal epoch.
Cap is applied during block forging and block application.
Cap application is controlled by a 1.4.0 fork

Reward from mainchain (ZenIP 42206) - additional constraint (max cap)

---

qa/sc_evm_rpc_eth.py
sdk/src/main/scala/io/horizen/account/api/rpc/service/RpcProcessor.scala
sdk/src/test/scala/io/horizen/account/api/http/route/AccountEthRpcRouteTest.scala

As documented in issue SDK-1660 we are reverting some code changes in the fix for returning an array of response object also in case of errors- in a json-rpc batch request
https://horizenlabs.atlassian.net/browse/SDK-1660?atlOrigin=eyJpIjoiOGMxNDAxOWRjMTlmNDUyNDlmOGRjMzgwYzdkZjg5YWYiLCJwIjoiaiJ9

json-rpc batch requests: Returning an array of response object also in case of errors
